# Generated by Django 6.0.2 on 2026-06-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wialon_user_id', models.CharField(blank=True)),
                ('authorizenet_profile_id', models.CharField(blank=True)),
                ('authorizenet_subscription_id', models.CharField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminus_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'terminus profile',
                'verbose_name_plural': 'terminus profiles',
            },
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
