import terminusgps_tracker.wialonapi.flags as flag

UNIT_BASIC_ACCESS_MASK = sum(
    [
        flag.ACCESSFLAG_VIEW_ITEM_BASIC,
        flag.ACCESSFLAG_VIEW_ITEM_DETAILED,
        flag.ACCESSFLAG_RENAME_ITEM,
        flag.ACCESSFLAG_VIEW_CUSTOM_FIELDS,
        flag.ACCESSFLAG_MANAGE_CUSTOM_FIELDS,
        flag.ACCESSFLAG_VIEW_ADMIN_FIELDS,
        flag.ACCESSFLAG_MANAGE_ICON,
        flag.ACCESSFLAG_QUERY_REPORTS,
        flag.ACCESSFLAG_VIEW_ATTACHED_FILES,
        flag.ACCESSFLAG_UNIT_EXECUTE_COMMANDS,
        flag.ACCESSFLAG_UNIT_VIEW_SERVICE_INTERVALS,
        flag.ACCESSFLAG_UNIT_REGISTER_EVENTS,
        flag.ACCESSFLAG_UNIT_IMPORT_MESSAGES,
        flag.ACCESSFLAG_UNIT_EXPORT_MESSAGES,
    ]
)

UNIT_FULL_ACCESS_MASK = flag.ACCESSFLAG_FULL_ACCESS
