from django.db import models
from django.utils.translation import gettext_lazy as _


class CountryCode(models.TextChoices):
    US = "USA", _("United States")
    BR = "Brazil", _("Brazil")
    CA = "Canada", _("Canada")
    MX = "Mexico", _("Mexico")


class USState(models.TextChoices):
    AL = "Alabama", _("Alabama")
    AK = "Alaska", _("Alaska")
    AZ = "Arizona", _("Arizona")
    AR = "Arkansas", _("Arkansas")
    CA = "California", _("California")
    CO = "Colorado", _("Colorado")
    CT = "Conneticut", _("Conneticut")
    DE = "Delaware", _("Delaware")
    FL = "Florida", _("Florida")
    GA = "Georgia", _("Georgia")
    HI = "Hawaii", _("Hawaii")
    ID = "Idaho", _("Idaho")
    IL = "Illinois", _("Illinois")
    IN = "Indiana", _("Indiana")
    IA = "Iowa", _("Iowa")
    KS = "Kansas", _("Kansas")
    KY = "Kentucky", _("Kentucky")
    LA = "Louisiana", _("Louisiana")
    ME = "Maine", _("Maine")
    MD = "Maryland", _("Maryland")
    MA = "Massachusetts", _("Massachusetts")
    MI = "Michigan", _("Michigan")
    MN = "Minnesota", _("Minnesota")
    MS = "Mississippi", _("Mississippi")
    MO = "Missouri", _("Missouri")
    MT = "Montana", _("Montana")
    NE = "Nebraska", _("Nebraska")
    NV = "Nevada", _("Nevada")
    NH = "New Hampshire", _("New Hampshire")
    NJ = "New Jersey", _("New Jersey")
    NM = "New Mexico", _("New Mexico")
    NY = "New York", _("New York")
    NC = "North Carolina", _("North Carolina")
    ND = "North Dakota", _("North Dakota")
    OH = "Ohio", _("Ohio")
    OK = "Oklahoma", _("Oklahoma")
    OR = "Oregon", _("Oregon")
    PA = "Pennslyvania", _("Pennslyvania")
    RI = "Rhode Island", _("Rhode Island")
    SC = "South Carolina", _("South Carolina")
    SD = "South Dakota", _("South Dakota")
    TN = "Tennessee", _("Tennessee")
    TX = "Texas", _("Texas")
    UT = "Utah", _("Utah")
    VT = "Vermont", _("Vermont")
    VA = "Virginia", _("Virginia")
    WA = "Washington", _("Washington")
    WV = "West Virginia", _("West Virginia")
    WI = "Wisconsin", _("Wisconsin")
    WY = "Wyoming", _("Wyoming")
