from django.db import models
from django.utils.translation import gettext_lazy as _


class CountryChoice(models.TextChoices):
    US = "USA", _("United States")
    CA = "Canada", _("Canada")
    MX = "Mexico", _("México")


class CanadaStateChoice(models.TextChoices):
    AB = "Alberta", _("Alberta")
    BC = "British Columbia", _("British Columbia")
    MB = "Manitoba", _("Manitoba")
    NB = "New Brunswick", _("New Brunswick")
    NL = "Newfoundland and Labrador", _("Newfoundland & Labrador")
    NS = "Nova Scotia", _("Nova Scotia")
    ON = "Ontario", _("Ontario")
    PE = "Prince Edward Island", _("Prince Edward Island")
    QC = "Quebec", _("Quebec")
    SK = "Saskatchewan", _("Saskatchewan")


class MexicoStateChoice(models.TextChoices):
    AG = "Aguascalientes", _("Aguascalientes")
    BN = "Baja California", _("Baja California")
    BS = "Baja California Sur", _("Baja California Sur")
    CP = "Campeche", _("Campeche")
    CS = "Chiapas", _("Chiapas")
    CI = "Chihuahua", _("Chihuahua")
    CH = "Coahuila", _("Coahuila")
    CL = "Colima", _("Colima")
    DF = "Mexico City", _("Mexico City")
    DG = "Durango", _("Durango")
    GJ = "Guanajuato", _("Guanajuato")
    GE = "Guerrero", _("Guerrero")
    HD = "Hidalgo", _("Hidalgo")
    JA = "Jalisco", _("Jalisco")
    MX = "Mexico", _("México")
    MC = "Michoacan", _("Michoacán")
    MR = "Morelos", _("Morelos")
    NA = "Nayarit", _("Nayarit")
    NL = "Nuevo Leon", _("Nuevo León")
    OA = "Oaxaca", _("Oaxaca")
    PU = "Puebla", _("Puebla")
    QE = "Queretaro", _("Querétaro")
    QI = "Quintana Roo", _("Quintana Roo")
    SL = "San Luis Potosi", _("San Luis Potosí")
    SI = "Sinaloa", _("Sinaloa")
    SO = "Sonora", _("Sonora")
    TB = "Tabasco", _("Tabasco")
    TA = "Tamaulipas", _("Tamaulipas")
    TL = "Tlaxcala", _("Tlaxcala")
    VC = "Veracruz", _("Veracruz")
    YU = "Yucatan", _("Yucatán")
    ZA = "Zacatecas", _("Zacatecas")


class USStateChoice(models.TextChoices):
    AL = "Alabama", _("Alabama")
    AK = "Alaska", _("Alaska")
    AZ = "Arizona", _("Arizona")
    AR = "Arkansas", _("Arkansas")
    CA = "California", _("California")
    CO = "Colorado", _("Colorado")
    CT = "Conneticut", _("Conneticut")
    DE = "Delaware", _("Delaware")
    FL = "Florida", _("Florida")
    GA = "Georgia", _("Georgia")
    HI = "Hawaii", _("Hawaii")
    ID = "Idaho", _("Idaho")
    IL = "Illinois", _("Illinois")
    IN = "Indiana", _("Indiana")
    IA = "Iowa", _("Iowa")
    KS = "Kansas", _("Kansas")
    KY = "Kentucky", _("Kentucky")
    LA = "Louisiana", _("Louisiana")
    ME = "Maine", _("Maine")
    MD = "Maryland", _("Maryland")
    MA = "Massachusetts", _("Massachusetts")
    MI = "Michigan", _("Michigan")
    MN = "Minnesota", _("Minnesota")
    MS = "Mississippi", _("Mississippi")
    MO = "Missouri", _("Missouri")
    MT = "Montana", _("Montana")
    NE = "Nebraska", _("Nebraska")
    NV = "Nevada", _("Nevada")
    NH = "New Hampshire", _("New Hampshire")
    NJ = "New Jersey", _("New Jersey")
    NM = "New Mexico", _("New Mexico")
    NY = "New York", _("New York")
    NC = "North Carolina", _("North Carolina")
    ND = "North Dakota", _("North Dakota")
    OH = "Ohio", _("Ohio")
    OK = "Oklahoma", _("Oklahoma")
    OR = "Oregon", _("Oregon")
    PA = "Pennslyvania", _("Pennslyvania")
    RI = "Rhode Island", _("Rhode Island")
    SC = "South Carolina", _("South Carolina")
    SD = "South Dakota", _("South Dakota")
    TN = "Tennessee", _("Tennessee")
    TX = "Texas", _("Texas")
    UT = "Utah", _("Utah")
    VT = "Vermont", _("Vermont")
    VA = "Virginia", _("Virginia")
    WA = "Washington", _("Washington")
    WV = "West Virginia", _("West Virginia")
    WI = "Wisconsin", _("Wisconsin")
    WY = "Wyoming", _("Wyoming")
