# Generated by Django 6.0.5 on 2026-06-18 16:18

import django.core.validators
import django.db.models.deletion
import terminusgps_installer.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'installer',
                'verbose_name_plural': 'installers',
            },
        ),
        migrations.CreateModel(
            name='InstallJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete')], default='started')),
                ('resource', models.CharField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('imei', models.CharField(validators=[django.core.validators.MinLengthValidator(15), terminusgps_installer.validators.validate_imei])),
                ('vin', models.CharField(blank=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17), terminusgps_installer.validators.validate_vin])),
                ('mileage', models.PositiveIntegerField(blank=True)),
                ('license', models.CharField(blank=True)),
                ('crt_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='terminusgps_installer.installer')),
            ],
            options={
                'verbose_name': 'install job',
                'verbose_name_plural': 'install jobs',
            },
        ),
    ]
