# Generated by Django 5.2.2 on 2025-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonasset',
            name='vin',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='wialonasset',
            name='imei',
            field=models.CharField(blank=True, default=None, max_length=19, null=True),
        ),
    ]
