# Generated by Django 6.0.5 on 2026-06-18 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='vin',
            field=models.CharField(blank=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
    ]
