# Generated by Django 5.1.9 on 2025-05-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WialonAsset',
        ),
    ]
