# Generated by Django 5.1.9 on 2025-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonasset',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
