# Generated by Django 6.0.5 on 2026-06-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0002_alter_installjob_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installjob',
            name='license',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='mileage',
        ),
    ]
