# Generated by Django 5.1.9 on 2025-05-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0002_wialonasset_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installjob',
            options={'verbose_name': 'install job', 'verbose_name_plural': 'install jobs'},
        ),
        migrations.RemoveField(
            model_name='wialonasset',
            name='icon',
        ),
        migrations.AddField(
            model_name='wialonasset',
            name='imei',
            field=models.CharField(default=869738060092801, max_length=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wialonassetcommand',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='terminusgps_installer.wialonasset'),
        ),
    ]
