# Generated by Django 5.1.9 on 2025-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0002_delete_wialonasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='accounts',
        ),
        migrations.AddField(
            model_name='installer',
            name='accounts',
            field=models.ManyToManyField(blank=True, default=None, related_name='installers', to='terminusgps_installer.wialonaccount'),
        ),
    ]
