# Generated by Django 5.1.9 on 2025-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0003_alter_installjob_options_remove_wialonasset_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installjob',
            name='status',
            field=models.CharField(choices=[('CT', 'Created'), ('ON', 'On-going'), ('CP', 'Completed')], default='CT', max_length=2),
        ),
    ]
