# Generated by Django 6.0.5 on 2026-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0003_remove_installjob_license_remove_installjob_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('needs_billing', 'Needs billing'), ('complete', 'Complete')], default='started'),
        ),
    ]
