# Generated by Django 6.0.5 on 2026-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0004_alter_installjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='status',
            field=models.CharField(choices=[('needs_billing', 'Needs billing'), ('done', 'Done')], default='needs_billing'),
        ),
    ]
