# Generated by Django 5.1.9 on 2025-05-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0004_installjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('ON', 'On-going'), ('CP', 'Completed')], default='CR', max_length=2),
        ),
    ]
