# Generated by Django 5.1.9 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0005_alter_installjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installjob',
            name='status',
        ),
        migrations.AddField(
            model_name='installjob',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
