# Generated by Django 6.0.5 on 2026-06-19 17:51

import django.core.validators
import django.db.models.deletion
import terminusgps_installer.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0005_alter_installjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installjob',
            name='installer',
        ),
        migrations.AlterModelOptions(
            name='installjob',
            options={'get_latest_by': 'crt_date', 'ordering': ['crt_date'], 'verbose_name': 'install job', 'verbose_name_plural': 'install jobs'},
        ),
        migrations.AlterField(
            model_name='installjob',
            name='imei',
            field=models.CharField(help_text='Provide the 15-digit IMEI number present on the tracking device.', unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15), terminusgps_installer.validators.validate_imei]),
        ),
        migrations.AlterField(
            model_name='installjob',
            name='resource',
            field=models.CharField(help_text='Select a Wialon resource from the list.', validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='installjob',
            name='vin',
            field=models.CharField(blank=True, help_text="Optional. Provide the vehicle's 17-character VIN number.", validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17), terminusgps_installer.validators.validate_vin]),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.AddField(
            model_name='installjob',
            name='employee',
            field=models.ForeignKey(default=1, help_text='Select the employee responsible for this job.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='terminusgps_installer.employee'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Installer',
        ),
    ]
