# Generated by Django 5.1.9 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0006_remove_installjob_status_installjob_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonassetcommand',
            name='cmd_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wialonassetcommand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='wialonassetcommand',
            unique_together={('asset', 'cmd_id')},
        ),
    ]
