# Generated by Django 6.0.5 on 2026-06-22 19:11

import django.core.validators
import django.db.models.deletion
import terminusgps_installer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0006_remove_installjob_installer_alter_installjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='imei',
            field=models.CharField(help_text='Provide the 15-digit IMEI number present on the tracking device. Ex: 869738060092801', unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15), terminusgps_installer.validators.validate_imei]),
        ),
        migrations.AlterField(
            model_name='installjob',
            name='vin',
            field=models.CharField(blank=True, help_text="Optional. Provide the vehicle's 17-character VIN number. Ex: JTHBA30G065155212", validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17), terminusgps_installer.validators.validate_vin]),
        ),
        migrations.CreateModel(
            name='WialonRenderingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendering_session', to='terminusgps_installer.installjob')),
            ],
        ),
    ]
