# Generated by Django 5.1.9 on 2025-05-28 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0007_wialonassetcommand_cmd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='terminusgps_installer.wialonasset'),
        ),
    ]
