# Generated by Django 6.0.5 on 2026-06-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0007_alter_installjob_imei_alter_installjob_vin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonMapRenderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_renderer', to='terminusgps_installer.installjob')),
            ],
        ),
        migrations.DeleteModel(
            name='WialonRenderingSession',
        ),
    ]
