# Generated by Django 5.1.9 on 2025-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0008_alter_installjob_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonassetcommand',
            name='cmd_type',
            field=models.CharField(choices=[('block_engine', 'Block Engine'), ('unblock_engine', 'Unblock Engine'), ('custom_msg', 'Custom Message'), ('driver_msg', 'Driver Message'), ('download_msgs', 'Download Messages'), ('query_pos', 'Query Position'), ('query_photo', 'Query Photo'), ('output_on', 'Output On'), ('output_off', 'Output Off'), ('send_pos', 'Send Position'), ('set_report_interval', 'Set Report Interval'), ('upload_cfg', 'Upload Configuration'), ('upload_sw', 'Upload Firmware')], default='custom_msg', max_length=64),
        ),
        migrations.AddField(
            model_name='wialonassetcommand',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
