# Generated by Django 6.0.5 on 2026-06-22 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0008_wialonmaprenderer_delete_wialonrenderingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonmaprenderer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_renderers', to='terminusgps_installer.installjob'),
        ),
    ]
