# Generated by Django 5.1.9 on 2025-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0009_wialonassetcommand_cmd_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonaccount',
            name='uid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wialonaccount',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
