# Generated by Django 5.1.9 on 2025-05-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0010_wialonaccount_uid_alter_wialonaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='accounts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='terminusgps_installer.wialonaccount'),
        ),
    ]
