# Generated by Django 6.0.5 on 2026-06-24 16:49

import django.core.validators
import terminusgps_installer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0010_wialonmap_delete_wialonmaprenderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='imei',
            field=models.CharField(help_text='Provide the 15-digit IMEI number present on the tracking device. Ex: 869738060092801', unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15), terminusgps_installer.validators.validate_imei]),
        ),
    ]
