# Generated by Django 6.0.5 on 2026-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0011_alter_installjob_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='installjob',
            name='locator_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='WialonMap',
        ),
    ]
