# Generated by Django 6.0.5 on 2026-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0012_installjob_locator_url_delete_wialonmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='installjob',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='installjob',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='installjob',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='installjob',
            name='image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
