# Generated by Django 6.0.5 on 2026-06-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0013_installjob_image_1_installjob_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installjob',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='image_4',
        ),
    ]
