# Generated by Django 6.0.5 on 2026-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0014_remove_installjob_image_1_remove_installjob_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installjob',
            name='license_plate',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='installjob',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installjob',
            name='vehicle_id',
            field=models.CharField(blank=True),
        ),
    ]
