# Generated by Django 6.0.5 on 2026-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0015_installjob_license_plate_installjob_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='license_plate',
            field=models.CharField(blank=True, help_text="Optional. Provide the vehicle's license plate number."),
        ),
        migrations.AlterField(
            model_name='installjob',
            name='mileage',
            field=models.IntegerField(blank=True, help_text="Optional. Provide the vehicle's current mileage."),
        ),
    ]
