# Generated by Django 6.0.5 on 2026-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0016_alter_installjob_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='mileage',
            field=models.IntegerField(blank=True, default=None, help_text="Optional. Provide the vehicle's current mileage.", null=True),
        ),
    ]
