# Generated by Django 6.0.5 on 2026-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0017_alter_installjob_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='vehicle_id',
            field=models.CharField(blank=True, help_text="Optional. Provide the vehicle's client-designated identifier. Ex: Truck #13"),
        ),
    ]
