# Generated by Django 6.0.5 on 2026-06-29 17:39

import django.core.validators
import terminusgps_installer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0019_installjobattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installjob',
            name='imei',
            field=models.CharField(help_text='Provide the 5-20 digit IMEI number present on the tracking device. Ex: 869738060092801', unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20), terminusgps_installer.validators.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='installjob',
            name='vin',
            field=models.CharField(blank=True, help_text="Optional. Provide the vehicle's 17 character VIN number. Ex: JTHBA30G065155212", validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17), terminusgps_installer.validators.validate_vin]),
        ),
        migrations.DeleteModel(
            name='InstallJobAttachment',
        ),
    ]
