# Generated by Django 6.0.5 on 2026-06-29 18:36

import django.core.validators
import terminusgps_installer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0020_alter_installjob_imei_alter_installjob_vin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallJobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.AlterField(
            model_name='installjob',
            name='resource',
            field=models.CharField(help_text='Select a Wialon resource from the list.', validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), terminusgps_installer.validators.validate_is_digit]),
        ),
        migrations.AddField(
            model_name='installjob',
            name='attachments',
            field=models.ManyToManyField(related_name='jobs', to='terminusgps_installer.installjobattachment'),
        ),
    ]
