# Generated by Django 6.0.5 on 2026-06-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0021_installjobattachment_alter_installjob_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installjob',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='InstallJobAttachment',
        ),
    ]
