# Generated by Django 6.0.5 on 2026-07-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0023_installjobattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallJobAttachment',
        ),
    ]
