# Generated by Django 6.0.6 on 2026-07-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0024_delete_installjobattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonResource',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'wialon resource',
                'verbose_name_plural': 'wialon resources',
            },
        ),
        migrations.CreateModel(
            name='WialonUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('imei', models.CharField(max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('plate', models.CharField(blank=True, max_length=12)),
                ('mileage', models.PositiveIntegerField(blank=True, default=0)),
                ('locator_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='locator_url',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='installjob',
            name='vin',
        ),
        migrations.AlterField(
            model_name='installjob',
            name='employee',
            field=models.ForeignKey(help_text='Select an employee responsible for this job.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='terminusgps_installer.employee'),
        ),
        migrations.AddField(
            model_name='installjob',
            name='company',
            field=models.ForeignKey(default=1, help_text='Select a company.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='terminusgps_installer.wialonresource'),
            preserve_default=False,
        ),
    ]
