# Generated by Django 6.0.6 on 2026-07-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0025_wialonresource_wialonunit_remove_installjob_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonunit',
            name='job',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='terminusgps_installer.installjob'),
            preserve_default=False,
        ),
    ]
