# Generated by Django 6.0.7 on 2026-08-11 15:56

import terminusgps_installer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_installer', '0026_wialonunit_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonunit',
            name='imei',
            field=models.CharField(max_length=20, validators=[terminusgps_installer.validators.validate_is_digit]),
        ),
    ]
