# Generated by Django 6.0 on 2025-12-15 18:03

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminusgps_payments', '0002_alter_customerprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonAccount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='WialonUnit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='WialonUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='TerminusgpsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0825, help_text='Enter a tax rate as a decimal.', max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=24.99, help_text='Enter an amount to charge the customer every payment period.', max_digits=9)),
                ('tax', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '*', django.db.models.expressions.CombinedExpression(models.F('tax_rate'), '+', models.Value(1))), '-', models.F('subtotal')), help_text='Automatically generated tax amount.', output_field=models.DecimalField(decimal_places=2, max_digits=9))),
                ('grand_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('subtotal'), '*', django.db.models.expressions.CombinedExpression(models.F('tax_rate'), '+', models.Value(1))), help_text='Automatically generated grand total amount (subtotal+tax).', output_field=models.DecimalField(decimal_places=2, max_digits=9))),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminusgps_customer', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminusgps_customer', to='terminusgps_payments.subscription')),
                ('wialon_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_manager.wialonuser')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
    ]
