# Generated by Django 6.0 on 2026-01-15 21:08

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminusgps_payments', '0002_alter_customeraddressprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonResource',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('crt', models.IntegerField(blank=True, editable=False, verbose_name='creator id')),
                ('bact', models.IntegerField(blank=True, editable=False, verbose_name='account id')),
                ('uacl', models.IntegerField(blank=True, editable=False, verbose_name='user access control level')),
                ('bpact', models.IntegerField(blank=True, editable=False, verbose_name='parent account id')),
                ('plan', models.CharField(blank=True, default='terminusgps_ext_hist')),
                ('is_account', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'wialon resource',
                'verbose_name_plural': 'wialon resources',
            },
        ),
        migrations.CreateModel(
            name='WialonUnit',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('crt', models.IntegerField(blank=True, editable=False, verbose_name='creator id')),
                ('bact', models.IntegerField(blank=True, editable=False, verbose_name='account id')),
                ('uacl', models.IntegerField(blank=True, editable=False, verbose_name='user access control level')),
                ('imei', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'wialon unit',
                'verbose_name_plural': 'wialon units',
            },
        ),
        migrations.CreateModel(
            name='WialonUser',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('crt', models.IntegerField(blank=True, editable=False, verbose_name='creator id')),
                ('bact', models.IntegerField(blank=True, editable=False, verbose_name='account id')),
                ('uacl', models.IntegerField(blank=True, editable=False, verbose_name='user access control level')),
            ],
            options={
                'verbose_name': 'wialon user',
                'verbose_name_plural': 'wialon users',
            },
        ),
        migrations.CreateModel(
            name='TerminusGPSCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('24.95'), help_text='Enter a dollar amount to charge the customer monthly.', max_digits=9)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0825'), help_text='Enter a tax rate to charge the customer sales tax.', max_digits=9)),
                ('tax_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sub_total'), '*', django.db.models.expressions.CombinedExpression(models.F('tax_rate'), '*', models.Value(1))), help_text='Automatically generated tax amount to collect from the customer.', output_field=models.DecimalField(decimal_places=2, max_digits=9))),
                ('grand_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sub_total'), '+', models.F('tax_total')), help_text='Automatically generated total amount (base+tax) to collect from the customer.', output_field=models.DecimalField(decimal_places=2, max_digits=9))),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminusgpscustomer', to='terminusgps_payments.subscription')),
                ('user', models.OneToOneField(help_text='Select a Django user associated with the customer.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wialon_resource', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='terminusgps_manager.wialonresource')),
                ('wialon_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='terminusgps_manager.wialonuser')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
    ]
