# Generated by Django 6.0.1 on 2026-01-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminusgpscustomer',
            name='wialon_units',
        ),
        migrations.DeleteModel(
            name='WialonUnit',
        ),
    ]
