# Generated by Django 6.0 on 2026-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonresource',
            name='bact',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='wialonunit',
            name='bact',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='bact',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='account id'),
        ),
    ]
