# Generated by Django 6.0.5 on 2026-06-11 17:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('city', models.CharField(blank=True)),
                ('state', models.CharField(blank=True)),
                ('message', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name': 'contact form response',
                'verbose_name_plural': 'contact form responses',
            },
        ),
    ]
