# Generated by Django 6.0 on 2026-01-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminusgpscustomer',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminusgpscustomer', to='terminusgps_payments.subscription'),
        ),
    ]
