# Generated by Django 6.0 on 2026-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonresource',
            name='plan',
            field=models.CharField(default='terminusgps_ext_hist'),
        ),
    ]
