# Generated by Django 5.2.8 on 2025-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonresource',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
    ]
