# Generated by Django 6.0 on 2026-01-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0002_alter_wialonresource_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonresource',
            name='is_account',
        ),
        migrations.RemoveField(
            model_name='wialonresource',
            name='plan',
        ),
    ]
