# Generated by Django 6.0.5 on 2026-06-11 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0002_contactformresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformresponse',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
