# Generated by Django 6.0 on 2026-01-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0002_alter_wialonresource_bact_alter_wialonunit_bact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonresource',
            name='bpact',
        ),
    ]
