# Generated by Django 6.0 on 2026-01-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0003_remove_wialonresource_bpact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonresource',
            name='bact',
            field=models.IntegerField(blank=True, editable=False, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='wialonunit',
            name='bact',
            field=models.IntegerField(blank=True, editable=False, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='wialonuser',
            name='bact',
            field=models.IntegerField(blank=True, editable=False, verbose_name='account id'),
        ),
    ]
