# Generated by Django 6.0.5 on 2026-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0003_contactformresponse_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformresponse',
            name='message',
            field=models.TextField(max_length=2048),
        ),
    ]
