# Generated by Django 6.0 on 2026-01-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_manager', '0003_remove_wialonresource_is_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonresource',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wialonresource',
            name='plan',
            field=models.CharField(blank=True, default='terminusgps_ext_hist'),
        ),
    ]
