# Generated by Django 5.1.1 on 2024-12-02 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerSubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.IntegerField(blank=True, choices=[(5, 'Low'), (25, 'Mid'), (999, 'Inf')], default=None, null=True)),
            ],
            options={
                'verbose_name': 'subscription feature',
                'verbose_name_plural': 'subscription features',
            },
        ),
        migrations.CreateModel(
            name='TrackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizenet_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('wialon_group_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('wialon_resource_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('wialon_end_user_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('wialon_super_user_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='TrackerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('authorizenet_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='terminusgps_tracker.trackerprofile')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
        ),
        migrations.CreateModel(
            name='TrackerNotification',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('call', 'Notification via phone call'), ('sms', 'Notification via sms')], default='sms', max_length=4)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.trackerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('authorizenet_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='terminusgps_tracker.trackerprofile')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
            },
        ),
        migrations.CreateModel(
            name='TrackerSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('wialon_id', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('wialon_cmd', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('wialon_cmd_link', models.CharField(blank=True, choices=[('', 'Automatic link'), ('tcp', 'TCP'), ('udp', 'UDP'), ('vrt', 'Virtual'), ('gsm', 'SMS')], default='', max_length=3)),
                ('wialon_cmd_type', models.CharField(choices=[('block_engine', 'Block engine'), ('unblock_engine', 'Unblock engine'), ('custom_msg', 'Custom message'), ('driver_msg', 'Message to driver'), ('download_msgs', 'Download messages'), ('query_pos', 'Query position'), ('query_photo', 'Query snapshot'), ('output_on', 'Activate output'), ('output_off', 'Deactivate output'), ('send_position', 'Send coordinates'), ('set_report_interval', 'Set data transfer interval'), ('upload_cfg', 'Upload configuration'), ('upload_sw', 'Upload firmware')], default='upload_cfg', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (12, 'Annually')], default=1)),
                ('length', models.PositiveSmallIntegerField(choices=[(6, 'Half Year'), (12, 'Full Year')], default=12)),
                ('features', models.ManyToManyField(to='terminusgps_tracker.trackersubscriptionfeature')),
            ],
            options={
                'verbose_name': 'subscription tier',
                'verbose_name_plural': 'subscription tiers',
            },
        ),
        migrations.CreateModel(
            name='TrackerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizenet_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('terminated', 'Terminated')], default='suspended', max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='terminusgps_tracker.trackerprofile')),
                ('tier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='terminusgps_tracker.trackersubscriptiontier')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TrackerTodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to='terminusgps_tracker.trackerprofile')),
            ],
            options={
                'verbose_name': 'to-do list',
                'verbose_name_plural': 'to-do lists',
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('view', models.CharField(max_length=512)),
                ('is_complete', models.BooleanField(default=False)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='terminusgps_tracker.trackertodolist')),
            ],
            options={
                'verbose_name': 'to-do item',
                'verbose_name_plural': 'to-do items',
            },
        ),
    ]
