# Generated by Django 5.2.2 on 2025-08-28 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('terminusgps_tracker', '0001_initial'), ('terminusgps_tracker', '0002_customersubscription_prev_tier_and_more'), ('terminusgps_tracker', '0003_remove_customersubscription_prev_tier_and_more'), ('terminusgps_tracker', '0004_alter_subscriptionfeature_desc_and_more'), ('terminusgps_tracker', '0005_alter_customersubscription_status'), ('terminusgps_tracker', '0006_customer_verified'), ('terminusgps_tracker', '0007_customersubscription_prev_address_and_more'), ('terminusgps_tracker', '0008_remove_customersubscription_prev_address_and_more'), ('terminusgps_tracker', '0009_customersubscription__prev_address_and_more'), ('terminusgps_tracker', '0010_rename_verified_customer_email_verified_and_more'), ('terminusgps_tracker', '0011_remove_customer_wialon_group_id_and_more'), ('terminusgps_tracker', '0012_customerasset_name'), ('terminusgps_tracker', '0013_alter_customersubscription_total_months'), ('terminusgps_tracker', '0014_alter_customer_options'), ('terminusgps_tracker', '0015_alter_customer_options'), ('terminusgps_tracker', '0016_alter_customer_options'), ('terminusgps_tracker', '0017_remove_customersubscription__prev_address_and_more'), ('terminusgps_tracker', '0018_alter_customershippingaddress_options'), ('terminusgps_tracker', '0019_alter_customersubscription_trial_months'), ('terminusgps_tracker', '0020_customercoupon'), ('terminusgps_tracker', '0021_alter_customerasset_options_and_more'), ('terminusgps_tracker', '0022_customercoupon_datetime_redeemed_and_more'), ('terminusgps_tracker', '0023_remove_customercoupon_customer_and_more'), ('terminusgps_tracker', '0024_rename_authoriznet_profile_id_customer_authorizenet_profile_id'), ('terminusgps_tracker', '0025_subscription_delete_customersubscription'), ('terminusgps_tracker', '0026_alter_customer_options_and_more'), ('terminusgps_tracker', '0027_alter_subscription_options'), ('terminusgps_tracker', '0028_customerpaymentmethod_default_and_more'), ('terminusgps_tracker', '0029_subscription_start_date'), ('terminusgps_tracker', '0030_remove_customerwialonunit_customer_and_more'), ('terminusgps_tracker', '0031_customerwialonunit'), ('terminusgps_tracker', '0032_alter_customerwialonunit_options'), ('terminusgps_tracker', '0033_alter_customerwialonunit_customer_and_more'), ('terminusgps_tracker', '0034_alter_customer_authorizenet_profile_id_and_more'), ('terminusgps_tracker', '0035_alter_subscription_tier'), ('terminusgps_tracker', '0036_customerwialonunit_vin_alter_customerwialonunit_imei'), ('terminusgps_tracker', '0037_alter_subscription_options_and_more'), ('terminusgps_tracker', '0038_customerwialonunit_tier'), ('terminusgps_tracker', '0039_subscription_units'), ('terminusgps_tracker', '0040_alter_subscription_address_and_more'), ('terminusgps_tracker', '0041_subscriptionfeature_total'), ('terminusgps_tracker', '0042_alter_subscriptionfeature_desc_and_more'), ('terminusgps_tracker', '0043_customerpaymentmethod_cc_last_4_and_more'), ('terminusgps_tracker', '0044_alter_subscription_address_and_more'), ('terminusgps_tracker', '0045_alter_customerwialonunit_tier'), ('terminusgps_tracker', '0046_subscription_start_date'), ('terminusgps_tracker', '0047_remove_subscription_features_and_more'), ('terminusgps_tracker', '0048_customersubscriptiontier_and_more'), ('terminusgps_tracker', '0049_remove_customersubscriptiontier_desc_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wialon_user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('wialon_resource_id', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('authorizenet_profile_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='terminusgps_tracker.customer')),
                ('cc_last_4', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('cc_type', models.CharField(blank=True, default=None, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'customer payment method',
                'verbose_name_plural': 'customer payment methods',
            },
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='terminusgps_tracker.customer')),
            ],
            options={
                'verbose_name': 'customer shipping address',
                'verbose_name_plural': 'customer shipping addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=24.99, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='suspended', max_length=16)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customershippingaddress')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customerpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWialonUnit',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='terminusgps_tracker.customer')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customersubscriptiontier')),
            ],
            options={
                'verbose_name': 'customer wialon unit',
                'verbose_name_plural': 'customer wialon units',
            },
        ),
    ]
