# Generated by Django 5.1.4 on 2024-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackersubscriptionfeature',
            name='amount',
        ),
    ]
