# Generated by Django 5.1.5 on 2025-02-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerpaymentmethod',
            old_name='is_default',
            new_name='default',
        ),
        migrations.RenameField(
            model_name='trackershippingaddress',
            old_name='is_default',
            new_name='default',
        ),
    ]
