# Generated by Django 5.1.7 on 2025-04-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='prev_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_tier', to='terminusgps_tracker.subscriptiontier'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='terminusgps_tracker.customershippingaddress'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='terminusgps_tracker.customerpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier', to='terminusgps_tracker.subscriptiontier'),
        ),
    ]
