# Generated by Django 5.2.6 on 2025-09-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0002_alter_addressprofile_options_and_more'),
        ('terminusgps_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='authorizenet_profile_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.OneToOneField(default=522862742, on_delete=django.db.models.deletion.CASCADE, to='terminusgps_payments.customerprofile'),
            preserve_default=False,
        ),
    ]
