# Generated by Django 5.1.5 on 2025-02-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0002_rename_is_default_trackerpaymentmethod_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerasset',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='trackernotification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trackerasset',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='trackerasset',
            name='icon',
        ),
        migrations.DeleteModel(
            name='TrackerAssetCommand',
        ),
        migrations.DeleteModel(
            name='TrackerNotification',
        ),
    ]
