# Generated by Django 5.1.4 on 2024-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0002_remove_trackersubscriptionfeature_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersubscriptionfeature',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='trackernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
