# Generated by Django 5.2.6 on 2025-09-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0002_remove_customer_authorizenet_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='customer_profile',
        ),
    ]
