# Generated by Django 5.1.8 on 2025-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0002_customersubscription_prev_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='prev_tier',
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='total_months',
            field=models.PositiveIntegerField(choices=[(12, '1 year'), (24, '2 years')], default=12),
        ),
    ]
