# Generated by Django 5.1.8 on 2025-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0003_remove_customersubscription_prev_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='desc',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='desc',
            field=models.TextField(max_length=1024),
        ),
    ]
