# Generated by Django 5.1.4 on 2024-12-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0003_trackersubscriptionfeature_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerAsset',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hw_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('imei_number', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.trackerprofile')),
            ],
        ),
    ]
