# Generated by Django 5.2.6 on 2025-09-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0003_rename_profile_customer_customer_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerWialonUnitTier',
            new_name='SubscriptionTier',
        ),
        migrations.AlterModelOptions(
            name='customerwialonunit',
            options={'verbose_name': 'wialon unit', 'verbose_name_plural': 'wialon units'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontier',
            options={'verbose_name': 'subscription tier', 'verbose_name_plural': 'subscription tiers'},
        ),
    ]
