# Generated by Django 5.2.6 on 2025-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0004_rename_customerwialonunittier_subscriptiontier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0825, max_digits=5),
        ),
    ]
