# Generated by Django 5.1.8 on 2025-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0004_alter_subscriptionfeature_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('created', 'Created'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='created', max_length=16),
        ),
    ]
