# Generated by Django 5.2.6 on 2025-09-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0005_customer_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwialonunit',
            name='imei',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
