# Generated by Django 5.1.8 on 2025-04-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0006_customer_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='prev_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_address', to='terminusgps_tracker.customershippingaddress'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='prev_payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_payment', to='terminusgps_tracker.customerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='prev_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_tier', to='terminusgps_tracker.subscriptiontier'),
        ),
    ]
