# Generated by Django 5.2.6 on 2025-09-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0002_alter_addressprofile_options_and_more'),
        ('terminusgps_tracker', '0006_customerwialonunit_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_profile',
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_payments.subscription'),
        ),
        migrations.AddField(
            model_name='customerwialonunit',
            name='wialon_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='imei',
            field=models.CharField(help_text='Enter the IMEI # found on your installed device.', max_length=16),
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Enter a memorable name.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='tier',
            field=models.ForeignKey(help_text='Select a tier.', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='terminusgps_tracker.subscriptiontier'),
        ),
    ]
