# Generated by Django 5.1.4 on 2024-12-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0006_trackerasset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersubscription',
            name='address_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trackersubscription',
            name='payment_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
