# Generated by Django 5.1.8 on 2025-04-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0007_customersubscription_prev_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='prev_address',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='prev_payment',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='prev_tier',
        ),
    ]
