# Generated by Django 5.1.4 on 2024-12-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0007_trackersubscription_address_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackerasset',
            options={'verbose_name': 'asset', 'verbose_name_plural': 'assets'},
        ),
    ]
