# Generated by Django 5.1.8 on 2025-04-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0008_remove_customersubscription_prev_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='_prev_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_address', to='terminusgps_tracker.customershippingaddress'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='_prev_payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_payment', to='terminusgps_tracker.customerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='_prev_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_tier', to='terminusgps_tracker.subscriptiontier'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('unbound', 'Unbound'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='unbound', max_length=16),
        ),
    ]
