# Generated by Django 5.1.4 on 2024-12-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0008_alter_trackerasset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerAssetCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(choices=[('', 'Auto'), ('tcp', 'TCP'), ('udp', 'UDP'), ('vrt', 'Virtual'), ('gsm', 'SMS')], default='', max_length=64)),
                ('type', models.CharField(choices=[('block_engine', 'Block Engine'), ('unblock_engine', 'Unblock Engine'), ('custom_msg', 'Custom Message'), ('driver_msg', 'Message to Driver'), ('download_msgs', 'Download messages'), ('query_pos', 'Query Position'), ('query_photo', 'Query Snapshot'), ('output_on', 'Activate Output'), ('output_off', 'Deactive Output'), ('send_position', 'Send Coordinates'), ('set_report_interval', 'Set Data Transfer Interval'), ('upload_cfg', 'Upload Configuration'), ('upload_sw', 'Upload Firmware')], default='upload_cfg', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='trackerasset',
            name='commands',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.trackerassetcommand'),
        ),
    ]
