# Generated by Django 5.1.4 on 2024-12-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0009_trackerassetcommand_trackerasset_commands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackerassetcommand',
            options={'verbose_name': 'asset command', 'verbose_name_plural': 'asset commands'},
        ),
        migrations.RemoveField(
            model_name='trackerasset',
            name='commands',
        ),
        migrations.AlterField(
            model_name='trackerassetcommand',
            name='link',
            field=models.CharField(blank=True, choices=[('', 'Auto'), ('tcp', 'TCP'), ('udp', 'UDP'), ('vrt', 'Virtual'), ('gsm', 'SMS')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='trackerassetcommand',
            name='type',
            field=models.CharField(choices=[('block_engine', 'Block Engine'), ('unblock_engine', 'Unblock Engine'), ('custom_msg', 'Custom Message'), ('driver_msg', 'Message to Driver'), ('download_msgs', 'Download messages'), ('query_pos', 'Query Position'), ('query_photo', 'Query Snapshot'), ('output_on', 'Activate Output'), ('output_off', 'Deactive Output'), ('send_position', 'Send Coordinates'), ('set_report_interval', 'Set Data Transfer Interval'), ('upload_cfg', 'Upload Configuration'), ('upload_sw', 'Upload Firmware')], default='custom_msg', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerasset',
            name='commands',
            field=models.ManyToManyField(blank=True, default=None, to='terminusgps_tracker.trackerassetcommand'),
        ),
    ]
