# Generated by Django 5.1.8 on 2025-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0010_rename_verified_customer_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wialon_group_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wialon_super_user_id',
        ),
    ]
