# Generated by Django 5.1.4 on 2024-12-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0010_alter_trackerassetcommand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackerprofile',
            options={'permissions': [('view_subscription_commands', 'Can view subscription asset commands'), ('view_destructive_commands', 'Can view destructive asset commands')], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
