# Generated by Django 5.1.8 on 2025-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0011_remove_customer_wialon_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerasset',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
