# Generated by Django 5.1.4 on 2025-01-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0012_alter_trackerassetcommand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerasset',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='terminusgps_tracker.trackerprofile'),
        ),
    ]
