# Generated by Django 5.1.5 on 2025-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0013_alter_trackerasset_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerasset',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trackersubscriptionfeature',
            name='desc',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
