# Generated by Django 5.1.8 on 2025-04-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0014_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_add_asset', 'Can add an asset')]},
        ),
    ]
