# Generated by Django 5.1.5 on 2025-01-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0014_trackerasset_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerasset',
            name='image',
        ),
    ]
