# Generated by Django 5.1.5 on 2025-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0016_trackerasset_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerasset',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='icon/'),
        ),
    ]
