# Generated by Django 5.1.8 on 2025-05-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0017_remove_customersubscription__prev_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customershippingaddress',
            options={'verbose_name': 'customer shipping address', 'verbose_name_plural': 'customer shipping addresses'},
        ),
    ]
