# Generated by Django 5.1.9 on 2025-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0018_alter_customershippingaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='trial_months',
            field=models.PositiveIntegerField(choices=[(0, '0 months'), (12, '12 months'), (24, '24 months')], default=0),
        ),
    ]
