# Generated by Django 5.1.9 on 2025-05-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0020_customercoupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerasset',
            options={'verbose_name': 'asset', 'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='customercoupon',
            options={'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
        migrations.AlterModelOptions(
            name='customerpaymentmethod',
            options={'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='customershippingaddress',
            options={'verbose_name': 'shipping address', 'verbose_name_plural': 'shipping addresses'},
        ),
        migrations.AlterModelOptions(
            name='customersubscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
    ]
