# Generated by Django 5.1.9 on 2025-05-14 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0021_alter_customerasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercoupon',
            name='datetime_redeemed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='trial_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='total_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='trial_months',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36)]),
        ),
    ]
