# Generated by Django 5.2.1 on 2025-06-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0022_customercoupon_datetime_redeemed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercoupon',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='customerpaymentmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customershippingaddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='authorizenet_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='authorizenet_id',
        ),
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='default',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='authorizenet_id',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='default',
        ),
        migrations.AddField(
            model_name='customer',
            name='authoriznet_profile_id',
            field=models.IntegerField(default=522862742),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='wialon_resource_id',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='wialon_user_id',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerpaymentmethod',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustomerWialonAccount',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='terminusgps_tracker.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWialonUnit',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('imei', models.CharField(blank=True, default=None, max_length=19, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='terminusgps_tracker.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerAsset',
        ),
        migrations.DeleteModel(
            name='CustomerCoupon',
        ),
    ]
