# Generated by Django 5.2.1 on 2025-06-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0023_remove_customercoupon_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='authoriznet_profile_id',
            new_name='authorizenet_profile_id',
        ),
    ]
