# Generated by Django 5.2.1 on 2025-06-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0024_rename_authoriznet_profile_id_customer_authorizenet_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('terminated', 'Terminated')], default=None, max_length=64, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.customer')),
                ('tier', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.subscriptiontier')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
    ]
