# Generated by Django 5.2.1 on 2025-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0027_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
