# Generated by Django 5.2.1 on 2025-06-04 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0028_customerpaymentmethod_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
