# Generated by Django 5.2.1 on 2025-06-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0030_remove_customerwialonunit_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWialonUnit',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('imei', models.PositiveBigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.customer')),
            ],
        ),
    ]
