# Generated by Django 5.2.1 on 2025-06-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0031_customerwialonunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerwialonunit',
            options={'verbose_name': 'customer wialon unit', 'verbose_name_plural': 'customer wialon units'},
        ),
    ]
