# Generated by Django 5.2.1 on 2025-06-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0032_alter_customerwialonunit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwialonunit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='terminusgps_tracker.customer'),
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='imei',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
