# Generated by Django 5.2.1 on 2025-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0033_alter_customerwialonunit_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='authorizenet_profile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wialon_resource_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wialon_user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
