# Generated by Django 5.2.1 on 2025-06-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0034_alter_customer_authorizenet_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.subscriptiontier'),
        ),
    ]
