# Generated by Django 5.2.2 on 2025-06-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0036_customerwialonunit_vin_alter_customerwialonunit_imei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='features',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.ManyToManyField(blank=True, default=None, to='terminusgps_tracker.subscriptionfeature'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='Default', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.customershippingaddress'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.customerpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='suspended', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='desc',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
