# Generated by Django 5.2.2 on 2025-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0038_customerwialonunit_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='units',
            field=models.ManyToManyField(blank=True, default=None, to='terminusgps_tracker.customerwialonunit'),
        ),
    ]
