# Generated by Django 5.2.2 on 2025-06-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0039_subscription_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.customershippingaddress'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_tracker.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminusgps_tracker.customerpaymentmethod'),
        ),
    ]
