# Generated by Django 5.2.2 on 2025-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0040_alter_subscription_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionfeature',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
