# Generated by Django 5.2.2 on 2025-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0041_subscriptionfeature_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeature',
            name='desc',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='desc',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
