# Generated by Django 5.2.2 on 2025-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0042_alter_subscriptionfeature_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='cc_last_4',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='cc_type',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
