# Generated by Django 5.2.2 on 2025-06-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0043_customerpaymentmethod_cc_last_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.OneToOneField(default=523484828, on_delete=django.db.models.deletion.PROTECT, to='terminusgps_tracker.customershippingaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='terminusgps_tracker.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(default=535832690, on_delete=django.db.models.deletion.PROTECT, to='terminusgps_tracker.customerpaymentmethod'),
            preserve_default=False,
        ),
    ]
