# Generated by Django 5.2.2 on 2025-07-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0044_alter_subscription_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwialonunit',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminusgps_tracker.subscriptiontier'),
        ),
    ]
