# Generated by Django 5.2.2 on 2025-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0045_alter_customerwialonunit_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
