# Generated by Django 5.2.2 on 2025-08-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0046_subscription_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='features',
        ),
        migrations.DeleteModel(
            name='SubscriptionFeature',
        ),
    ]
