# Generated by Django 5.2.2 on 2025-08-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0047_remove_subscription_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='cc_last_4',
        ),
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='cc_type',
        ),
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='default',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='default',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='street',
        ),
        migrations.RemoveField(
            model_name='customerwialonunit',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='customerwialonunit',
            name='vin',
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='suspended', max_length=16)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customershippingaddress')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customerpaymentmethod')),
            ],
        ),
        migrations.AlterField(
            model_name='customerwialonunit',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='terminusgps_tracker.customersubscriptiontier'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionTier',
        ),
    ]
