# Generated by Django 5.2.2 on 2025-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_tracker', '0048_customersubscriptiontier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscriptiontier',
            name='desc',
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='cc_last_4',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='cc_type',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customersubscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24.99, max_digits=9),
        ),
    ]
