# Generated by Django 5.2.2 on 2025-08-28 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "terminusgps_tracker",
            "0001_initial_squashed_0049_remove_customersubscriptiontier_desc_and_more",
        )
    ]

    operations = [
        migrations.RunPython(
            create_subscription_tiers, reverse_create_subscription_tiers
        )
    ]
