# Generated by Django 6.0.7 on 2026-09-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='header_subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='header_title',
            field=models.CharField(blank=True),
        ),
    ]
