# Generated by Django 6.1.1 on 2026-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='show_last_updated',
            field=models.BooleanField(default=False),
        ),
    ]
