# Generated by Django 6.0.7 on 2026-09-14 19:21

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_standardpage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='formpage',
            name='header_subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='header_title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=128, verbose_name='Call to Action Text'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
