# Generated by Django 6.0.7 on 2026-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_formpage_intro_formpage_header_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
