# Generated by Django 6.0.7 on 2026-09-15 15:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_formfield_placeholder'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_headline',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_headline',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_headline',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
