# Generated by Django 5.0.4 on 2024-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignupSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('opted_in', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=64)),
                ('asset_name', models.CharField(max_length=256)),
                ('imei', models.IntegerField()),
                ('phone', models.CharField(max_length=24)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
