# Generated by Django 5.0.4 on 2024-05-15 18:05

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dforms', '0002_newslettersignupsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignupsubmission',
            name='date_submitted',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='registrationformsubmission',
            name='date_submitted',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
