module.exports = {
	content: [
		"../templates/**/*.html",
		"../../templates/**/*.html",
		"../../**/templates/**/*.html",
		"../../**/forms/*.py",
		"../**/forms/*.py",
		"!../../**/node_modules",
		"../../**/*.js",
	],
	theme: {
		extend: {
			colors: {
				"terminus-black": "#0B090A",
				"terminus-red-900": "#660708",
				"terminus-red-800": "#760B0D",
				"terminus-red-700": "#850F11",
				"terminus-red-600": "#951316",
				"terminus-red-500": "#A4161A",
				"terminus-red-400": "#BA181B",
				"terminus-red-300": "#C52023",
				"terminus-red-200": "#D0282B",
				"terminus-red-100": "#DB3033",
				"terminus-red-50": "#E5383B",
				"terminus-gray-900": "#161A1D",
				"terminus-gray-800": "#2A2C2F",
				"terminus-gray-700": "#3D3E40",
				"terminus-gray-600": "#646162",
				"terminus-gray-500": "#8B8484",
				"terminus-gray-400": "#B1A7A6",
				"terminus-gray-300": "#D3D3D3",
				"terminus-gray-200": "#E4E3E4",
				"terminus-gray-100": "#F5F3F4",
				"terminus-white": "#FFFFFF",
			},
			typography: ({ theme }) => ({
				terminus: {
					css: {
						"--tw-prose-body": theme("colors.terminus-gray-700"),
						"--tw-prose-headings": theme("colors.terminus-gray-900"),
						"--tw-prose-lead": theme("colors.terminus-gray-800"),
						"--tw-prose-links": theme("colors.terminus-red-200"),
						"--tw-prose-bold": theme("colors.terminus-red-700"),
						"--tw-prose-counters": theme("colors.terminus-red-50"),
						"--tw-prose-bullets": theme("colors.terminus-red-800"),
						"--tw-prose-hr": theme("colors.terminus-gray-900"),
						"--tw-prose-quotes": theme("colors.terminus-gray-900"),
						"--tw-prose-quote-borders": theme("colors.terminus-red-700"),
						"--tw-prose-captions": theme("colors.terminus-gray-900"),
						"--tw-prose-code": theme("colors.terminus-gray-900"),
						"--tw-prose-pre-code": theme("colors.terminus-gray-900"),
						"--tw-prose-pre-bg": theme("colors.terminus-gray-900"),
						"--tw-prose-th-borders": theme("colors.terminus-red-800"),
						"--tw-prose-td-borders": theme("colors.terminus-red-400"),
						"--tw-prose-invert-body": theme("colors.terminus-gray-300"),
						"--tw-prose-invert-headings": theme("colors.terminus-gray-100"),
						"--tw-prose-invert-lead": theme("colors.terminus-gray-200"),
						"--tw-prose-invert-links": theme("colors.terminus-red-700"),
						"--tw-prose-invert-bold": theme("colors.terminus-red-100"),
						"--tw-prose-invert-counters": theme("colors.terminus-gray-900"),
						"--tw-prose-invert-bullets": theme("colors.terminus-red-50"),
						"--tw-prose-invert-hr": theme("colors.terminus-gray-900"),
						"--tw-prose-invert-quotes": theme("colors.terminus-gray-300"),
						"--tw-prose-invert-quote-borders": theme("colors.terminus-red-600"),
						"--tw-prose-invert-captions": theme("colors.terminus-gray-200"),
						"--tw-prose-invert-code": theme("colors.terminus-gray-200"),
						"--tw-prose-invert-pre-code": theme("colors.terminus-gray-900"),
						"--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
						"--tw-prose-invert-th-borders": theme("colors.terminus-red-400"),
						"--tw-prose-invert-td-borders": theme("colors.terminus-red-800"),
					},
				},
			}),
		},
	},
	plugins: [
		/**
		 * '@tailwindcss/forms' is the forms plugin that provides a minimal styling
		 * for forms. If you don't like it or have own styling for forms,
		 * comment the line below to disable '@tailwindcss/forms'.
		 */
		//require('@tailwindcss/forms'),
		require("@tailwindcss/typography"),
		require("@tailwindcss/aspect-ratio"),
	],
};
