# Generated by Django 5.1.8 on 2025-04-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_install', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wialon_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='terminusgps_install.wialonaccount')),
            ],
        ),
    ]
