# Generated by Django 5.1.8 on 2025-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_install', '0003_installer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='accounts',
        ),
        migrations.AddField(
            model_name='installer',
            name='accounts',
            field=models.ManyToManyField(related_name='accounts', to='terminusgps_install.wialonaccount'),
        ),
    ]
