# Generated by Django 5.1.8 on 2025-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_install', '0004_remove_installer_accounts_installer_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='accounts',
            field=models.ManyToManyField(related_name='installers', to='terminusgps_install.wialonaccount'),
        ),
    ]
